font:
  normal:
    family: monospace
    style: Regular

  bold:
    family: monospace
    style: Bold

  italic:
    family: monospace
    style: Italic

  bold_italic:
    family: monospace
    style: Bold Italic

  size: 12

key_bindings:
  - { key: P,   mods: Control|Shift,    chars: "\x1bp" }
  - { key: Key1,   mods: Control,       chars: "\x1b1"  }
  - { key: Key2,   mods: Control,       chars: ""  }
  - { key: Key3,   mods: Control,       chars: ""  }
  - { key: Key4,   mods: Control,       chars: ""  }
  - { key: Key5,   mods: Control,       chars: ""  }
  - { key: Key6,   mods: Control,       chars: ""  }
  - { key: Key7,   mods: Control,       chars: ""  }
  - { key: Key8,   mods: Control,       chars: ""  }
  - { key: Key9,   mods: Control,       chars: ""  }
  - { key: Key0,   mods: Control,       chars: ""  }
  - { key: Slash,   mods: Control,       chars: "\\c "  }
  #- { key: F,   mods: Control,       chars: "\x1b:Rg\n"  }

env:
  TERM: xterm-256color
